### ISSUE TITLE
Caching/Preloading Contributions

### ISSUE THREAD

**Issue by mktcode** [utopian-io/join.utopian.io#25]
At the moment the contributions for a selected project are always loaded from the API again and again while cycling through the project carousel. Would be great to have some kind of caching or preloading.
I decided to fetch the contributions on demand because the more projects we add the longer the initial requests will take. But there are better solutions.

![loading gif](https://user-images.githubusercontent.com/6792578/33072416-c36c362c-cebf-11e7-8475-bf48f7af5795.gif)

To be honest the relevant code got a bit messy because I had a hard time making jquery, the slick slider, gsap animations and VueJS work together.

See:
https://github.com/utopian-io/utopian-io-landingpage/blob/f7ab09e81237178986fe0e0daf65edfe3fb22ece/assets/js/index.js#L186

**Comment by muluha** [comment]
this is a wonderful
