### ISSUE TITLE
Performance/Loadtime

### ISSUE THREAD

**Issue by mktcode** [utopian-io/join.utopian.io#27]
Currently there are a ton of requests and nothing has been optimized for performance so far.

![performance](https://user-images.githubusercontent.com/6792578/33075952-774d3c4e-cecb-11e7-8517-7ab378c82e5c.png)

Many possibilites to improve this.

See:
https://developers.google.com/speed/pagespeed/insights/?url=join.utopian.io

**Comment by spiritualmatters** [comment]
Utopian.io's load performance has been zero for past 72 hours. Login remains in SteemConnect's perpetual loop. There's a lot of 'marketing'; but, being able to access the site seems more important.

**Comment by mktcode** [comment]
@spiritualmatters I haven't experienced any downtimes or issues like that. I'll pass this to @diegopucci but this discussion should focus on the landingpage. Thanks anyway, for reporting this.
