### ISSUE TITLE
Adding basic build process

### ISSUE THREAD

**Issue by olo2552** [utopian-io/join.utopian.io#71]
I think that even though that project is relatively small it deserves a webpack build process.
I don't say it needs to have all the bells and whistles, but the basic one is preety nice for further maintanance. 
## Advantages:
- multiple environments: better development experience- auto refresh splitting code acress multiple files
- eslint: stable code look using the same preset as utopian.io can make code more consistent, and linting can save us from a lot of bugs and unnersersary code
- vue code splitting: instead of edditing couple of huge files we can split all the logic and strucutre across components, which are far bettter for maintatnence. 
- using entire vue potential and dropping jquery support: in 2018: we can use vue for all login and throw out jquery, which is harder to maintain and increasing load time
- ES6+ usage - with webpack we don't need to care about ES5 way of dealing problems - build process allow to use all new ES proposals.
## Possible solution:
Fortunately, the code is using VueJS, so implementing entire webpack workflow should be very simple using VueCLI - I assume, that my one workday can include both implementing build process and refactor existing code.

If you consider this issue valid - let me know, I can take care of that.

**Comment by mktcode** [comment]
Next version will be properly built on VueJS webpack template.
