### ISSUE TITLE
No Login button. Can't Sign In

### ISSUE THREAD

**Issue by DrSensor** [utopian-io/join.utopian.io#81]
Hello, I have Steemit account but I can't find login button in https://utopian.io ?
I try the Sign Up button and then Sign In, but it directs me only to https://steemit.com
![utopian-failed-signin](https://user-images.githubusercontent.com/4953069/39955512-2b11c492-55fa-11e8-8f80-4bd019c763de.gif)

**Comment by mktcode** [comment]
The utopian.io frontend is currently down so there's nothing to login to. You can use steemit.com or any other frontend to contribute. In the meantime a new frontend is in the working.
https://steemit.com/utopian-io/@utopian-io/utopian-now-contributions-are-welcome
